lua/sql/defs.lua, lua/sql/stmt.lua
Not done. Need to go :) Finishing that later
=> Removed unused stuff

lua/sql.lua, lua/sql/table.lua, test/auto/sql_spec.lua, test/auto/table_spec.lua
- sql:table accepts opts.schema, 
- if table doesn't exists on any table commands it will be recreated. if sql:drop is called then it will never be recreated.
- change self.tbl to self.name
=> sql:create accepts opts.schema

lua/sql.lua, test/auto/sql_spec.lua
=> fix insert not respecting defaluts and not nulls

README.md, lua/sql.lua, lua/sql/json.lua, test/auto/sql_spec.lua
=> lua tables serialization

README.md
Thanks for your help, just in case you want to mention it
=> Add Nix to the README

lua/sql/parser.lua, test/auto/parser_spec.lua
yet another lazy feature to make a key `integer primary key`
=> feat: id = true to get integer primary key

README.md, lua/sql/table.lua, test/auto/table_spec.lua
Lazy shortcut for t:get({ where = {}}). Useful only if the user want the first match
~~- [ ] fix twhere{key,value,key,value}~~
=> new method: t:where

README.md
The default installation note in the README.md doesn't work on Windows. Fixed it :)
=> Added Installation NOTE for Windows Users

doc/sql.txt, lua/sql.lua, lua/sql/table.lua
=> 📦 NEW: support emmylua completions

doc/sql.txt, lua/sql.lua, test/auto/sql_spec.lua
all sugar functions should be at root and have sql leading it
=> ♻️ REF: sugar functions is part with root

doc/sql.txt, lua/sql/table.lua, lua/sql/table/cache.lua, lua/sql/utils.lua, test/auto/table_spec.lua
try and close #73.
I can't keep maintaining this, too much complexity. In case anyone is planning to use cache or extend it for network operations. `table.cache` module has been added just for that case.
=> ✨ NEW: end support for builtin cache :(

doc/sql.txt, lua/sql.lua, test/auto/sql_spec.lua
add support for doing `julianday() - julianday(row.timestamp)) * 24 * 60`.
=> ⚡️ ENH: sugar functions support for multiply

.github/workflows/changelog.yml, .github/workflows/docgen.yml, doc/sql.txt, lua/sql/table.lua, test/auto/table_spec.lua
=> :sparkles: table each and map accept function as first argument

.github/workflows/changelog.yml
=> :construction_worker: changelog run once every two days

.github/chglog/CHANGELOG.tpl.md, .github/chglog/config.yml, .github/workflows/changelog.yml, .github/workflows/docgen.yml
=> :construction_worker: update changelog format

lua/sql/stmt.lua, test/auto/sql_spec.lua
=> :bug: parser set values to nil when using sql function

doc/sqlite.txt, lua/sqlite/db.lua, lua/sqlite/init.lua, lua/sqlite/stmt.lua, lua/sqlite/utils.lua
According @Conni2461, sqlite.lua require time takes `4.140682` ms. 
I will try to adopt https://github.com/tjdevries/lazy.nvim/blob/master/lua/lazy.lua
approach and see if that improves it. credit @tjdevries
=> :zap: improve sqlite require time

README.md
I had some issues getting this set up on OSX earlier today, but everything is working fine with these changes. Thanks for your hard work!
=> Update Nix installation instructions

lua/sqlite/defs.lua
This fixes the error in linux as the path found it automatically was wrong so I made a check for linux right above mac os one
=> linux_libsqlite.so_path_fixed

lua/sqlite/db.lua
Related to https://github.com/kkharji/sqlite.lua/issues/162
=> Close connection in with_open if an error occurs

lua/sqlite/defs.lua
PR for this issue: https://github.com/kkharji/sqlite.lua/issues/166
=> feat(clib): add libsqlite3.so.0 as a lookup option

README.md
Just a cleanup to show a proper way to get the library extension automatically.
=> readme: update nix instructions
